version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  
  build:
    commands:
      - yum install dos2unix -y
      - sudo dos2unix *
  post_build:
    commands:
      - echo Build completed
# Include only the files required for your application to run.
artifacts:
  files:
    - src/**
    - scripts/*.sh
    - public/**
    - package.json
    - appspec.yml